# Домашее задание №2

## Задание
Откройте файл с информацией о мобильных приложениях из Apple Store "AppleStore.csv".

В нём содержаться следующие переменные:

    - "n": номер приложения 
    - "id" : идентификатор приложения
    - "track_name": название приложения
    - "size_bytes": размер в байтах
    - "currency": тип валюты, в которой измеряется цена
    - "price": цена
    - "rating_count_tot": суммарное число оценок пользователей (для всех версий)
    - "rating_count_ver": суммарное число оценок пользователей (для текущей версии)
    - "user_rating" : средняя оценка пользователей (для всех версий)
    - "user_rating_ver": средняя оценка пользователей (для текущей версии)
    - "ver": код последней версии 
    - "cont_rating": возрастное ограничение контента
    - "prime_genre": основной жанр 
    - "sup_devices.num": количество поддерживающих устройств
    - "ipadSc_urls.num": количество скриншотов в описании
    - "lang.num": число поддерживаемых языков
    - "vpp_lic": лицензирование на основе устройства Vpp

Обратите внимание, что все пункты задания должны сопровождаться _выполненным_ фрагментом кода!

## Выполните предложенные задания. Для каждого задания постройте графики, визуализирующие анализируемые взаимосвязи.

In [22]:
# 0.1. Прочитаем csv таблицу

import pandas as pd
df = pd.read_csv("AppleStore.csv", index_col=0)

### Задание 1. Проверка отличия распределения от «нормального»

Проанализируйте распределение значений всех метрических переменных. Проведите тест для проверки того отличается ли распределение значений переменных от нормального распределения. Сформулируйте гипотезы и выводы по результатам анализа. Постройте гистограммы распределения с наложенной кривой нормального распределения.

In [37]:
from scipy import stats 

# Используем тест на нормальность Колмогорова-Смирнова, так как размер выборки больше 50

stats.kstest(df.size_bytes.dropna(), 'norm')

stats.ks_2samp(df.size_bytes.dropna(), stats.lognorm(df.size_bytes.min(), df.size_bytes.max(), df.shape[0]))

# KstestResult(statistic=0.29022397024112323, pvalue=0.0)

# stats.kstest(df.price.dropna(), 'norm')
# # KstestResult(statistic=0.38363807348996043, pvalue=0.0)

# stats.kstest(df.rating_count_tot.dropna(), 'norm')
# # KstestResult(statistic=0.4324157321694819, pvalue=0.0)

# stats.kstest(df.rating_count_ver.dropna(), 'norm')
# # KstestResult(statistic=0.45326017607712143, pvalue=0.0)

# stats.kstest(df.user_rating.dropna(), 'norm')
# # KstestResult(statistic=0.2866452864263325, pvalue=0.0)


# stats.kstest(df.user_rating_ver.dropna(), 'norm')
# # KstestResult(statistic=0.27222517848783695, pvalue=0.0)

# df = df.rename(columns={'sup_devices.num': 'sup_devices_num'})

# stats.kstest(df.sup_devices_num.dropna(), 'norm')
# # KstestResult(statistic=0.4010000612326333, pvalue=0.0)

# df = df.rename(columns={'ipadSc_urls.num': 'ipadSc_urls_num'})
# stats.kstest(df.ipadSc_urls_num.dropna(), 'norm')
# # KstestResult(statistic=0.36815587659026167, pvalue=0.0)

# df = df.rename(columns={'lang.num': 'lang_num'})
# stats.kstest(df.lang_num.dropna(), 'norm')
# # KstestResult(statistic=0.29065334970897094, pvalue=0.0)

AxisError: axis -1 is out of bounds for array of dimension 0

### Задание 2. Тест Хи-квадрат

Проведите тест Хи-квадрат c тремя разными парами переменных, для которых он применим. Можно использовать как исходные переменные, так и перекодировать их. Постройте для выбранных пар переменных таблицы сопряженности и прокомментируйте их. Сформулируйте гипотезы. Интерпретируйте результаты анализа. Обоснуйте свои выводы.

In [43]:
ct_genre_cont_rating = pd.crosstab(df['prime_genre'], df['cont_rating'])
ct_genre_cont_rating
# stats.chi2_contingency(ct_price_userrating)

cont_rating        12+  17+    4+   9+
prime_genre
Book                20   18    63   11
Business             1    2    54    0
Catalogs             1    2     6    1
Education            8    7   432    6
Entertainment      108   98   285   44
Finance              5   24    75    0
Food & Drink        11    8    44    0
Games              741  177  2079  865
Health & Fitness    19   15   141    5
Lifestyle           12   39    88    5
Medical             14    4     5    0
Music               28    4   102    4
Navigation           4    2    40    0
News                29   23    18    5
Photo & Video       35   15   285   14
Productivity         2   14   158    4
Reference           12    6    44    2
Shopping            18   19    82    3
Social Networking   36   71    57    3
Sports              17   19    76    2
Travel               8    9    63    1
Utilities           22   44   170   12
Weather              4    2    66    0

In [45]:
ct_genre_licence = pd.crosstab(df['prime_genre'], df['vpp_lic'])
ct_genre_licence
# stats.chi2_contingency(ct_genre_licence)

vpp_lic             0     1
prime_genre
Book                0   112
Business            0    57
Catalogs            0    10
Education           0   453
Entertainment       1   534
Finance             0   104
Food & Drink        0    63
Games              33  3829
Health & Fitness    0   180
Lifestyle           0   144
Medical             0    23
Music               0   138
Navigation          1    45
News                3    72
Photo & Video       0   349
Productivity        1   177
Reference           0    64
Shopping            0   122
Social Networking   2   165
Sports              6   108
Travel              2    79
Utilities           1   247
Weather             0    72

In [47]:
ct_cont_rating_licence = pd.crosstab(df['cont_rating'], df['vpp_lic'])
ct_cont_rating_licence
stats.chi2_contingency(ct_cont_rating_licence)

(35.33217322435867,
 1.0364520358435337e-07,
 3,
 array([[8.02417674e+00, 1.14697582e+03],
        [4.32124496e+00, 6.17678755e+02],
        [3.07975545e+01, 4.40220245e+03],
        [6.85702376e+00, 9.80142976e+02]]))

### Задание 3. Парная корреляция
Проведите корреляционный анализ переменных (нужно рассмотреть не менее трёх разных пар переменных). Обоснуйте выбор рассчитываемых коэффициентов корреляции. Сформулируйте гипотезы. Интерпретируйте результаты анализа (значимость, сила и направление взаимосвязи). Заполните таблицу (не менее 3 записей).

In [9]:
import pandas as pd
d = {
     'Анализируемые пары переменных': ['---', '---', '---'],
     'Выбранный коэффициент корреляции (обоснование выбора)': ['---', '---', '---'],
     'Гипотеза': ['---', '---', '---'],
     'Сила взаимосвязи': ['---', '---', '---'],
     'Направление взаимосвязи': ['---', '---', '---'],
     'Статистическая значимость взамосвязи': ['---', '---', '---'],    
    
 }


df = pd.DataFrame(data=d)
df

,Анализируемые пары переменных,Выбранный коэффициент корреляции (обоснование выбора),Гипотеза,Сила взаимосвязи,Направление взаимосвязи,Статистическая значимость взамосвязи
0,---,---,---,---,---,---
1,---,---,---,---,---,---
2,---,---,---,---,---,---

## Задание 4. Частная корреляция
Посчитайте парный коэффициент корреляции между выбранной парой переменных. Посчитайте частный коэффициент корреляции между этими переменными, исключив влияние любой третьей переменной. Сделайте выводы.

# Этот файл нужно сохранить как Notebook (.ipynb) и загрузить в Smart LMS до 23:55 19 октября.